#pragma once

//Keyboard keys
#define GM_KEY_SPACE           32
#define GM_KEY_APOSTROPHE      39
#define GM_KEY_COMMA           44
#define GM_KEY_MINUS           45
#define GM_KEY_PERIOD          46
#define GM_KEY_SLASH           47
#define GM_KEY_0               48
#define GM_KEY_1               49
#define GM_KEY_2               50
#define GM_KEY_3               51
#define GM_KEY_4               52
#define GM_KEY_5               53
#define GM_KEY_6               54
#define GM_KEY_7               55
#define GM_KEY_8               56
#define GM_KEY_9               57
#define GM_KEY_SEMICOLON       59
#define GM_KEY_EQUAL           61
#define GM_KEY_A               65
#define GM_KEY_B               66
#define GM_KEY_C               67
#define GM_KEY_D               68
#define GM_KEY_E               69
#define GM_KEY_F               70
#define GM_KEY_G               71
#define GM_KEY_H               72
#define GM_KEY_I               73
#define GM_KEY_J               74
#define GM_KEY_K               75
#define GM_KEY_L               76
#define GM_KEY_M               77
#define GM_KEY_N               78
#define GM_KEY_O               79
#define GM_KEY_P               80
#define GM_KEY_Q               81
#define GM_KEY_R               82
#define GM_KEY_S               83
#define GM_KEY_T               84
#define GM_KEY_U               85
#define GM_KEY_V               86
#define GM_KEY_W               87
#define GM_KEY_X               88
#define GM_KEY_Y               89
#define GM_KEY_Z               90
#define GM_KEY_LEFT_BRACKET    91
#define GM_KEY_BACKSLASH       92
#define GM_KEY_RIGHT_BRACKET   93
#define GM_KEY_GRAVE_ACCENT    96
//Non-US #1
#define GM_KEY_WORLD_1         161
//Non-US #2
#define GM_KEY_WORLD_2         162

#define GM_KEY_ESCAPE          256
#define GM_KEY_ENTER           257
#define GM_KEY_TAB             258
#define GM_KEY_BACKSPACE       259
#define GM_KEY_INSERT          260
#define GM_KEY_DELETE          261
#define GM_KEY_RIGHT           262
#define GM_KEY_LEFT            263
#define GM_KEY_DOWN            264
#define GM_KEY_UP              265
#define GM_KEY_PAGE_UP         266
#define GM_KEY_PAGE_DOWN       267
#define GM_KEY_HOME            268
#define GM_KEY_END             269
#define GM_KEY_CAPS_LOCK       280
#define GM_KEY_SCROLL_LOCK     281
#define GM_KEY_NUM_LOCK        282
#define GM_KEY_PRINT_SCREEN    283
#define GM_KEY_PAUSE           284
#define GM_KEY_F1              290
#define GM_KEY_F2              291
#define GM_KEY_F3              292
#define GM_KEY_F4              293
#define GM_KEY_F5              294
#define GM_KEY_F6              295
#define GM_KEY_F7              296
#define GM_KEY_F8              297
#define GM_KEY_F9              298
#define GM_KEY_F10             299
#define GM_KEY_F11             300
#define GM_KEY_F12             301
#define GM_KEY_F13             302
#define GM_KEY_F14             303
#define GM_KEY_F15             304
#define GM_KEY_F16             305
#define GM_KEY_F17             306
#define GM_KEY_F18             307
#define GM_KEY_F19             308
#define GM_KEY_F20             309
#define GM_KEY_F21             310
#define GM_KEY_F22             311
#define GM_KEY_F23             312
#define GM_KEY_F24             313
#define GM_KEY_F25             314
#define GM_KEY_KP_0            320
#define GM_KEY_KP_1            321
#define GM_KEY_KP_2            322
#define GM_KEY_KP_3            323
#define GM_KEY_KP_4            324
#define GM_KEY_KP_5            325
#define GM_KEY_KP_6            326
#define GM_KEY_KP_7            327
#define GM_KEY_KP_8            328
#define GM_KEY_KP_9            329
#define GM_KEY_KP_DECIMAL      330
#define GM_KEY_KP_DIVIDE       331
#define GM_KEY_KP_MULTIPLY     332
#define GM_KEY_KP_SUBTRACT     333
#define GM_KEY_KP_ADD          334
#define GM_KEY_KP_ENTER        335
#define GM_KEY_KP_EQUAL        336
#define GM_KEY_LEFT_SHIFT      340
#define GM_KEY_LEFT_CONTROL    341
#define GM_KEY_LEFT_ALT        342
#define GM_KEY_LEFT_SUPER      343
#define GM_KEY_RIGHT_SHIFT     344
#define GM_KEY_RIGHT_CONTROL   345
#define GM_KEY_RIGHT_ALT       346
#define GM_KEY_RIGHT_SUPER     347
#define GM_KEY_MENU            348

//Mouse buttons
#define GM_MOUSE_BUTTON_1      0
#define GM_MOUSE_BUTTON_2      1
#define GM_MOUSE_BUTTON_3      2
#define GM_MOUSE_BUTTON_4      3
#define GM_MOUSE_BUTTON_5      4
#define GM_MOUSE_BUTTON_6      5
#define GM_MOUSE_BUTTON_7      6
#define GM_MOUSE_BUTTON_8      7
#define GM_MOUSE_BUTTON_LAST   GLFW_MOUSE_BUTTON_8
#define GM_MOUSE_BUTTON_LEFT   GLFW_MOUSE_BUTTON_1
#define GM_MOUSE_BUTTON_RIGHT  GLFW_MOUSE_BUTTON_2
#define GM_MOUSE_BUTTON_MIDDLE GLFW_MOUSE_BUTTON_3

//Joysticks
#define GM_JOYSTICK_1  0
#define GM_JOYSTICK_2  1
#define GM_JOYSTICK_3  2
#define GM_JOYSTICK_4  3
#define GM_JOYSTICK_5  4
#define GM_JOYSTICK_6  5
#define GM_JOYSTICK_7  6
#define GM_JOYSTICK_8  7
#define GM_JOYSTICK_9  8
#define GM_JOYSTICK_10 9
#define GM_JOYSTICK_11 10
#define GM_JOYSTICK_12 11
#define GM_JOYSTICK_13 12
#define GM_JOYSTICK_14 13
#define GM_JOYSTICK_15 14
#define GM_JOYSTICK_16 15